### PR TITLE
Improve View Appearances

### PR DESCRIPTION
**Pull request by caasion**
- made css classes' formatting consistent to Obsidian's
- updated timeline, weekly review, calendar view, and schedule view
- simplified command names (to make them shorter)

### CODE REVIEW

**Comment by YukiGasai** [comment]
Thank you very much for your contribution.
I will take a look at it 😊

**Review by YukiGasai — COMMENTED** [review]
We can update the command names.
If we update the names, we can make sure they are more consistent than currently. 
Example `Create gcal Event` and `List Google Events`. 
Maybe replace Google with gCal as well.

**Review by YukiGasai — CHANGES_REQUESTED** [review]
I think it's very good to adapt the obsidian naming schema, but I noticed some problems with the updated view. 

Could you remove the background color of the day container, as it really sticks out, especially when using none default themes?
image

The view no longer uses the remaining space, was this intended?
image

**Review by YukiGasai — COMMENTED** [review]
Thank you for cleaning up this mess and improving the week view. 😊
There is an issue when using the larger hour display, the view bugs out a little
image

**Review by YukiGasai — CHANGES_REQUESTED** [review]
Please make sure that the hour text is visible.
image

**Comment by caasion** [comment]
woah there are a lot of bugs I didn't catch. thanks for pointing them out! I've only been using a few views for myself and haven't really tried it in different ways. I'll be updating it whenever I have time. Do you have access to my fork to make changes? (I'm not sure how github works 100% so let me know if you want to make changes and need access)

**Comment by YukiGasai** [comment]
Hi @caasion,
please don't worry too much, I am very thankful for your additions. You can of course take your time. I have not that much time currently and suck at CSS ^^.
Because you selected `Maintainers are allowed to edit this pull request.` I should be able to push commits as well :)

**Comment by caasion** [comment]
> I think it's very good to adapt the obsidian naming schema, but I noticed some problems with the updated view.
> 
> Could you remove the background color of the day container, as it really sticks out, especially when using none default themes? image
> 
> The view no longer uses the remaining space, was this intended? image

I've removed the background color cus it really does stick out lol. Perhaps I could make another PR that makes the styling consistent with themes in the future.

It is intended that it doesn't use the remaining space (if you meant that the event would be in the same line as the time) since it kinda is too messy. Unless we change the time and give emphasis for the event name itself, it would look too overwhelming (too many characters in one line)

Let me know about your thoughts or any changes I need with the amendments

thank you!

**Comment by YukiGasai** [comment]
Hi, 
thank you for your changes.
The commands look very clean now and the timeline view looks great too.
I think that we should not remove the option of a wide schedule view because some people really want to use it. I see your point that it looks a little bit messy, but with a bigger font-weight on the event name, this should be okay. #87

**Comment by freqyfreqy** [comment]
I am MOST grateful for all of your work. If I may chime with my personal preference. I'd like on mobile for everything to fit so everything in separate rows is ok. On desktop, since I have a wider screen, I would prefer the time and the event description on the same row so that it appears (to me) cleaner and using space more efficiently. Just my personal preference and my vote. 
image

**Comment by caasion** [comment]
Is something like this what you are looking for?
image

The problem with that is when it is in the side bar, it becomes extremely messy. Some are wrapping and some aren't
image

So I am thinking we can have an option to toggle between the two options. What do you think?

**Comment by freqyfreqy** [comment]
> Is something like this what you are looking for? image
> 
> The problem with that is when it is in the side bar, it becomes extremely messy. Some are wrapping and some aren't image
> 
> So I am thinking we can have an option to toggle between the two options. What do you think?
> 
> Another option is for the wide view to be the default, and any event that overflows will just be ellipsis



> Is something like this what you are looking for? image
> 
> The problem with that is when it is in the side bar, it becomes extremely messy. Some are wrapping and some aren't image
> 
> So I am thinking we can have an option to toggle between the two options. What do you think?
> 
> Another option is for the wide view to be the default, and any event that overflows will just be ellipsis

I'd vote for the latter(this is probably something not worth having a separate configuration 'option' for). However I'm not sure what you mean by ellipsis?

Cheers and thank you for your help!

**Comment by caasion** [comment]
> I'd vote for the latter(this is probably something not worth having a separate configuration 'option' for). However I'm not sure what you mean by ellipsis?
> 
> Cheers and thank you for your help!

Ellpsis would be a compromise between wrapping and not. Right now, if some of the tasks are longer than the others, some wrap, but some don't, which makes for a disgusting sight. I could make all tasks not wrap, and when it overflows, it will be in ellpsis.

Something liek this?
Event is so long...   
Event that is shorter

**Comment by YukiGasai** [comment]
Sound like a great compromise to me.
Thank you for still working on this 😊

**Comment by freqyfreqy** [comment]
Yes, great compromise!

**Comment by caasion** [comment]
Sounds good! I will try to figure that out in the coming days.

Meanwhile, I have a feature request that comes with the schedule view. Is it possible for you to make the date formats convertible just like the timeline view? 
Eg. 08:20am-9:40pm (current) -> 8:20am-9:20pm (no leading zero) -> 8:20-21:20 (24 hour format with no leading zero)  -> 08:20-21:20 (24 hour format)

**Comment by caasion** [comment]
Finally managed to figure it out! Please review everything to make sure there aren't any more changes needed.

**Comment by YukiGasai** [comment]
Hi,
I check out your changes and it looks great. Thank you for your work, I will merge this now 😁.

**Comment by YukiGasai** [comment]
I am new to merging such large pull request. If you notice anything off, please feel free to address it.

**Comment by freqyfreqy** [comment]
Hi there! I was wondering how to change the font and size of these circled areas? I'm using the 'Style Settings' Plugin and can fonts from that plugin.

Screenshot 2023-04-04 at 12 38 59

**Pull request merged**
